# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{koi-vm}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Aaron Gough"]
  s.date = %q{2010-08-25}
  s.description = %q{A prototype Virtual Machine written in Ruby. Why would anyone write such a thing? Because it's fun, and it's a great learning tool.}
  s.email = %q{aaron@aarongough.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "README.rdoc",
     "Rakefile",
     "architecture.rdoc",
     "examples/blastoff.rb",
     "examples/hello_world.rb",
     "lib/.gitkeep",
     "test/.gitkeep",
     "test/performance/.gitignore",
     "test/performance/simple_benchmark.rb",
     "test/setup/test_unit_extensions.rb",
     "test/test_helper.rb",
     "test/unit/opcodes/comparative_operations/equal_test.rb",
     "test/unit/opcodes/comparative_operations/greater_than_test.rb",
     "test/unit/opcodes/comparative_operations/less_than_test.rb",
     "test/unit/opcodes/control_operations/exit_test.rb",
     "test/unit/opcodes/control_operations/no_op_test.rb",
     "test/unit/opcodes/flow_control_operations/jump_if_test.rb",
     "test/unit/opcodes/flow_control_operations/jump_test.rb",
     "test/unit/opcodes/flow_control_operations/jump_unless_test.rb",
     "test/unit/opcodes/function_operations/call_test.rb",
     "test/unit/opcodes/function_operations/push_function_test.rb",
     "test/unit/opcodes/function_operations/return_test.rb",
     "test/unit/opcodes/function_operations/tailcall_test.rb",
     "test/unit/opcodes/io_operations/gets_test.rb",
     "test/unit/opcodes/io_operations/print_test.rb",
     "test/unit/opcodes/math_operations/add_test.rb",
     "test/unit/opcodes/math_operations/divide_test.rb",
     "test/unit/opcodes/math_operations/multiply_test.rb",
     "test/unit/opcodes/math_operations/subtract_test.rb",
     "test/unit/opcodes/push_operations/push_bool_test.rb",
     "test/unit/opcodes/push_operations/push_float_test.rb",
     "test/unit/opcodes/push_operations/push_int_test.rb",
     "test/unit/opcodes/push_operations/push_nil_test.rb",
     "test/unit/opcodes/push_operations/push_string_test.rb",
     "test/unit/opcodes/stack_operations/dup_test.rb",
     "test/unit/opcodes/stack_operations/pop_test.rb",
     "test/unit/opcodes/stack_operations/stksize_test.rb",
     "test/unit/opcodes/stack_operations/swap_test.rb",
     "test/unit/opcodes/stack_operations/top_test.rb",
     "test/unit/opcodes/stack_operations/typeof_test.rb",
     "test/unit/opcodes/string_operations/concat_test.rb",
     "test/unit/opcodes/string_operations/strlen_test.rb",
     "test/unit/opcodes/string_operations/to_string_test.rb",
     "test/unit/opcodes/variable_operations/get_global_test.rb",
     "test/unit/opcodes/variable_operations/get_local_test.rb",
     "test/unit/opcodes/variable_operations/set_global_test.rb",
     "test/unit/opcodes/variable_operations/set_local_test.rb",
     "test/unit/vm_initialization_test.rb"
  ]
  s.homepage = %q{https://github.com/aarongough/koi}
  s.rdoc_options = ["--charset=UTF-8", "--line-numbers", "--inline-source"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{A prototype Virtual Machine written in Ruby}
  s.test_files = [
    "test/performance/simple_benchmark.rb",
     "test/setup/test_unit_extensions.rb",
     "test/test_helper.rb",
     "test/unit/opcodes/comparative_operations/equal_test.rb",
     "test/unit/opcodes/comparative_operations/greater_than_test.rb",
     "test/unit/opcodes/comparative_operations/less_than_test.rb",
     "test/unit/opcodes/control_operations/exit_test.rb",
     "test/unit/opcodes/control_operations/no_op_test.rb",
     "test/unit/opcodes/flow_control_operations/jump_if_test.rb",
     "test/unit/opcodes/flow_control_operations/jump_test.rb",
     "test/unit/opcodes/flow_control_operations/jump_unless_test.rb",
     "test/unit/opcodes/function_operations/call_test.rb",
     "test/unit/opcodes/function_operations/push_function_test.rb",
     "test/unit/opcodes/function_operations/return_test.rb",
     "test/unit/opcodes/function_operations/tailcall_test.rb",
     "test/unit/opcodes/io_operations/gets_test.rb",
     "test/unit/opcodes/io_operations/print_test.rb",
     "test/unit/opcodes/math_operations/add_test.rb",
     "test/unit/opcodes/math_operations/divide_test.rb",
     "test/unit/opcodes/math_operations/multiply_test.rb",
     "test/unit/opcodes/math_operations/subtract_test.rb",
     "test/unit/opcodes/push_operations/push_bool_test.rb",
     "test/unit/opcodes/push_operations/push_float_test.rb",
     "test/unit/opcodes/push_operations/push_int_test.rb",
     "test/unit/opcodes/push_operations/push_nil_test.rb",
     "test/unit/opcodes/push_operations/push_string_test.rb",
     "test/unit/opcodes/stack_operations/dup_test.rb",
     "test/unit/opcodes/stack_operations/pop_test.rb",
     "test/unit/opcodes/stack_operations/stksize_test.rb",
     "test/unit/opcodes/stack_operations/swap_test.rb",
     "test/unit/opcodes/stack_operations/top_test.rb",
     "test/unit/opcodes/stack_operations/typeof_test.rb",
     "test/unit/opcodes/string_operations/concat_test.rb",
     "test/unit/opcodes/string_operations/strlen_test.rb",
     "test/unit/opcodes/string_operations/to_string_test.rb",
     "test/unit/opcodes/variable_operations/get_global_test.rb",
     "test/unit/opcodes/variable_operations/get_local_test.rb",
     "test/unit/opcodes/variable_operations/set_global_test.rb",
     "test/unit/opcodes/variable_operations/set_local_test.rb",
     "test/unit/vm_initialization_test.rb",
     "examples/blastoff.rb",
     "examples/hello_world.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

